<?php
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Back in my Day</title>';
echo '<meta name="author" content="name">';
echo '<meta name="description" content="description here">';
echo '<meta name="keywords" content="keywords,here">';
echo '<link rel="shortcut icon" href="favicon.ico" type="image/vnd.microsoft.icon">';
echo '<link rel="stylesheet" href="//fonts.googleapis.com/css?family=font1|font2|etc" type="text/css">';
echo '<link href="https://fonts.googleapis.com/css?family=Varela+Round&display=swap" rel="stylesheet">';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">';
echo '<link rel="stylesheet" href="style.css" type="text/css">';
echo '<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>';
echo '</head>';
echo '<body>';
echo '<!-- Splash Screen -->';
echo '<div class="Splash-screen Splash-screen-bg ">';
echo '<img src="AppLogo_whiteOutline_sqTp.png" alt="Back in my Day Logo" width="500" height="auto" class="mx-auto d-block BIMD_logo">';
echo '<div class="form-outline d-flex justify-content-center mb-2">';
echo '<input type="search" id="splash_search" class="form-control w-50 p-3 BIMD_search" placeholder="Person, Place, or Thing" aria-label="Search" />';
echo '</div>';
echo '<div class="text-center BIMD_upload_btn">';
echo '<button id="UploadBtn" type="button" class="btn btn-primary justify-content-center" data-toggle="modal" data-target="#uploadModalCenter">Upload Your Images!</button>';
echo '</div>';
echo '</div>';
echo '<!-- Main Website -->';
echo '<div class="Main-container">';
echo '<nav class="navbar navbar-expand-lg navbar-light bg-light Splash-screen-bg">';
echo '<a class="navbar-brand" href="#">';
echo '<img src="AppLogo_whiteOutline.png" width="100" height="69" class="d-inline-block align-top" alt="">';
echo '</a>';
echo '<div class="d-flex mt-3 justify-content-start" id="navbarSupportedContent">';
echo '<ul class="navbar-nav mr-auto">';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#" style="color: white">History</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#" style="color: white">About</a>';
echo '</li>';
echo '</ul>';
echo '<form class="form-inline ml-3 input-large">';
echo '<input class="form-control BIMD_search" type="search" placeholder="Person, Place, or Thing" aria-label="Search">';
echo '<!--<button class="btn" type="submit">Search</button>-->';
echo '</form>';
echo '</div>';
echo '</nav>';
echo '<!--<img src="google-maps-test-image.png" alt="Duthie Speed School of Engineering" width = "100%" height="auto">-->';
echo '<!--<iframe width="100%" height="100%" style="border:0" loading="lazy" allowfullscreen src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC378FzdqDmer5FbeuT5tRIeM2h6YdWgzQ&q=Eiffel+Tower,Paris+France"></iframe>-->';
echo '<div id="map"></div>';
echo '</div>';
echo '<!-- Modal -->';
echo '<div class="modal fade" id="uploadModalCenter" tabindex="-1" role="dialog" aria-labelledby="uploadModalCenterTitle" aria-hidden="true">';
echo '<div class="modal-dialog modal-dialog-centered" role="document">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<h5 class="modal-title" id="uploadModalLongTitle">Upload Image</h5>';
echo '<button type="button" class="close" data-dismiss="modal" aria-label="Close">';
echo '<span aria-hidden="true">&times;</span>';
echo '</button>';
echo '</div>';
echo '<div class="modal-body">';
echo '<label for="img">Select image:</label>';
echo '<input type="file" id="img" name="img" accept="image/*">';
echo '<input type="submit">';
echo '</div>';
echo '<div class="modal-footer">';
echo '<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>';
echo '<button type="button" class="btn btn-primary">Save changes</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- JavaScript Bundle with Popper -->';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>';
echo '<script src="site.js"></script>';
echo '<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB41DRUbKWJHPxaFjMAwdrzWzbVKartNGg&callback=initMap&libraries=&v=weekly&channel=2"
      async ></script>';
echo '</body>';
echo '';
?>
